<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Faris Abiyyu">
<meta name="dcterms.date" content="2024-01-09">

<title>Pengaruh Ekspor Impor Terhadap PDB Indonesia Periode 2004-2022</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pengaruh Ekspor Impor Terhadap PDB Indonesia Periode 2004-2022</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Faris Abiyyu </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 9, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p><img src="poltekapp.jpg" class="img-fluid"></p>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Indonesia sebagai negara berkembang memiliki peran yang signifikan dalam perekonomian global. Pertumbuhan Ekonomi dan Perusahaan Domestik Bruto (PDB) menjadi indikator penting dalam mengukur kesejahteraan suatu negara. Dalam upaya untuk mencapai pertumbuhan ekonomi yang berkelanjutan, penting untuk memahami berbagai faktor yang memengaruhi kinerja ekonomi suatu negara.</p>
<p>Salah satu faktor yang memiliki peran krusial dalam perekonomian suatu negara adalah aktivitas ekspor dan impor. Ekspor dan impor merupakan dua elemen penting dalam perdagangan internasional yang dapat memberikan dampak signifikan terhadap PDB suatu negara. Oleh karena itu, analisis mendalam tentang pengaruh ekspor dan impor terhadap PDB menjadi sangat penting untuk memahami dinamika ekonomi Indonesia.</p>
<p>Periode 2004-2022 dipilih karena mencakup rentang waktu yang signifikan dan melibatkan peristiwa ekonomi penting, termasuk krisis keuangan global pada tahun 2008 dan pandemi COVID-19 pada tahun 2020. Dalam kurun waktu tersebut, Indonesia telah mengalami perubahan struktural dan kebijakan ekonomi yang mungkin mempengaruhi hubungan antara ekspor, impor, dan PDB.</p>
<p>Melalui penelitian ini, diharapkan dapat ditemukan hubungan yang lebih dalam antara ekspor, impor, dan PDB Indonesia. Penelitian ini diharapkan dapat memberikan kontribusi pada literatur ekonomi terkait hubungan antara ekspor, impor, dan PDB dalam konteks negara berkembang.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Ruang lingkup pembahasan masalah sesuai dengan variable yang akan digunakan pada analisis kali ini, yaitu Pengaruh Ekspor Impor Terhadap PDB pada periode 2004-2022 . Batasan masalah ini berperan untuk memfokuskan analisis dan pemahaman terhadap aspek-aspek tertentu yang relevan dengan tujuan penelitian.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<ol type="1">
<li>Apakah ekspor dan impor berpengaruh pada PDB Indonesia?</li>
<li>Bagaimana hubungan ekspor dan impor terhadap perubahan PDB Indonesia?</li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Tujuan utama dari penelitian ini adalah untuk mencari hubungan sederhana antara kegiatan ekspor dan impor dengan pertumbuhan ekonomi (PDB) Indonesia dari tahun 2004 hingga 2022. Menemukan faktor apa yang paling memengaruhi antara ekspor dan impor terhadap PBD (Produk Domestik Bruto).</p>
<p>Adapun manfaatnya adalah guna menjadikan penelitian ini sebagai sumber informasi bagi masyarakat dan edukasi bagi masyarakat terkait pengaruh ekspor dan impor terhadap PDB pada periode tercantum.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Untuk keperluan menunjang regresi multivariat yang dilakukan di Rstudio untuk penelitian ini antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(WDI)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<p>Kemajuan perkembangan ekonomi suatu negara adalah salah satu isu yang penting dalam perdebatan ekonomi. Suatu negara dapat mempercepat laju pertumbuhan ekonominya dengan meningkatkan dan mempromosikan ekspor barang dan jasa. Volume impor berhubungan negatif dengan harga relatif dan bervariasi positif dengan permintaan agregat (pertumbuhan PDB riil).(Siti Hodijah, 2021) PDB akan mengalami peningkatan bila nilai ekspor dari suatu negara mengalami meningkat. Ini menunjukkan bahwa barang atau jasa yang diproduksi oleh negara itu digemari oleh negara lain, hal itu berarti nilai ekspor mendominasi daripada nilai impor dan akan meningkatkan kegiatan ekonomi masyarakat. (Tri Puspandari, 2022)</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<p><img src="WORLD%20BANK.png" class="img-fluid"></p>
<table class="table">
<thead>
<tr class="header">
<th>TAHUN</th>
<th>EKSPOR (x)</th>
<th>IMPOR (S)</th>
<th>PDB (Y)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2004</td>
<td>82744351781</td>
<td>70744690514</td>
<td>2.568369e+11</td>
</tr>
<tr class="even">
<td>2005</td>
<td>97387627566</td>
<td>85533801154</td>
<td>2.858686e+11</td>
</tr>
<tr class="odd">
<td>2006</td>
<td>113143425288</td>
<td>93411754076</td>
<td>3.645705e+11</td>
</tr>
<tr class="even">
<td>2007</td>
<td>127226102177</td>
<td>109755093425</td>
<td>4.322167e+11</td>
</tr>
<tr class="odd">
<td>2008</td>
<td>152090401422</td>
<td>146706628549</td>
<td>5.102286e+11</td>
</tr>
<tr class="even">
<td>2009</td>
<td>130357798591</td>
<td>115216544854</td>
<td>5.395801e+11</td>
</tr>
<tr class="odd">
<td>2010</td>
<td>183480562961</td>
<td>169158027607</td>
<td>7.550942e+11</td>
</tr>
<tr class="even">
<td>2011</td>
<td>235095129136</td>
<td>212996885270</td>
<td>8.929691e+11</td>
</tr>
<tr class="odd">
<td>2012</td>
<td>225744403268</td>
<td>229362102380</td>
<td>9.178699e+11</td>
</tr>
<tr class="even">
<td>2013</td>
<td>218308408831</td>
<td>225519356300</td>
<td>9.125241e+11</td>
</tr>
<tr class="odd">
<td>2014</td>
<td>210820082828</td>
<td>217485215773</td>
<td>8.908148e+11</td>
</tr>
<tr class="even">
<td>2015</td>
<td>182158298805</td>
<td>178863652303</td>
<td>8.608542e+11</td>
</tr>
<tr class="odd">
<td>2016</td>
<td>177886012744</td>
<td>170835000833</td>
<td>9.318774e+11</td>
</tr>
<tr class="even">
<td>2017</td>
<td>204924485910</td>
<td>194777319199</td>
<td>1.015619e+12</td>
</tr>
<tr class="odd">
<td>2018</td>
<td>218905647885</td>
<td>230045612383</td>
<td>1.042272e+12</td>
</tr>
<tr class="even">
<td>2019</td>
<td>208057763662</td>
<td>213034646338</td>
<td>1.119100e+12</td>
</tr>
<tr class="odd">
<td>2020</td>
<td>183546577016</td>
<td>165646843305</td>
<td>1.059055e+12</td>
</tr>
<tr class="even">
<td>2021</td>
<td>254008548673</td>
<td>222939963036</td>
<td>1.186505e+12</td>
</tr>
<tr class="odd">
<td>2022</td>
<td>323079953660</td>
<td>275703237974</td>
<td>1.319100e+12</td>
</tr>
</tbody>
</table>
<p>Penelitian ini menggunakan data Exports of goods and service (current US$), Imports of goods and service (current US$) dan GDP (current US$) dari World Development Indicators (The World Bank)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"C:/Users/Xvby/Documents/UAS METEDOLOGI PENELITIAN"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'DATA UAS METODOLOGI PENELITIAN.xlsx'</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(y<span class="sc">~</span>x<span class="sc">+</span>s, <span class="at">data=</span>dat)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>m<span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>x,dat<span class="sc">$</span>m,<span class="at">xlab=</span><span class="st">"Ekspor"</span>,<span class="at">ylab=</span><span class="st">"error"</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>) <span class="co">#membuat garis horizontal di y=0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Plot pengaruh error terhadap Ekspor</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>m<span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>y,dat<span class="sc">$</span>m,<span class="at">xlab=</span><span class="st">"PDB"</span>,<span class="at">ylab=</span><span class="st">"error"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Plot pengaruh error terhadap PDB</p>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Teknik analisis yang digunakan dalam penelitian ini adalah teknik kuantitatif deskriptif. Metode yang dipilih adalah regresi multivariat dengan 2 variabel independen yaitu ekspor dan impor dan 1 variabel dependen yaitu PDB. Penelitian ini bertujuan untuk mencari hubungan antara ekspor (X) dan impor (S) dengan PDB (Y). Spesifikasi yang dilakukan adalah:</p>
<p><span class="math display">\[
Y=\beta_0 +\beta_1 X+\beta_2 S+\mu
\]</span></p>
<p>Di mana X adalah Ekspor Indonesia, S adalah Impor Indonesia, dan Y adalah PDB Indonesia.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<p>Pada bagian ini dapat ditampilkan data dan visualisasi data yang telah dikumpulkan.</p>
<table class="table">
<thead>
<tr class="header">
<th>Variable</th>
<th>Coefficient</th>
<th>Std.Error</th>
<th>t-value</th>
<th>Prob (.)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intecerpt</td>
<td>-1.080e+11</td>
<td>9.633e+13</td>
<td>-1.121</td>
<td>0.279</td>
</tr>
<tr class="even">
<td>X</td>
<td>2.551e+00</td>
<td>2.025e+00</td>
<td>1.260</td>
<td>0.226</td>
</tr>
<tr class="odd">
<td>S</td>
<td>2.507e+00</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>R&nbsp;squared</td>
<td>0.8632</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Adjusted&nbsp;R-Squared</td>
<td>0.8461</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>F-Statistic</td>
<td>50.46</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Prob(F-statistic)</td>
<td>1.229e-07</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>Berikut setelah data dimasukkan ke dalam rumus persamaan :</p>
<p><span class="math display">\[
Y= (-1.080) + 2.551 + 2.507 +\mu
\]</span></p>
<p>Dapat dilihat, bahwa Ekspor dan Impor bisa mempengaruhi peningkatan atau penurunan pada PDB Indonesia. Namun, dapat juga dilihat pada analisis kali ini bahwa Ekspor dan Impor juga tidak terlalu membuat perubahan yang signifikat pada PDB Indonesia.Ditandai dengan setiap kenaikan nilai ekspor dengan diasumsikan nilainya 1, maka dapat meningkatkan PDB sebesar 2.551 dan nilai impor 1 maka PDB akan ada peningkatan 2.507 dengan S yang sama.</p>
<p>Nilai Adjusted R-squared sebesar 0.8632 menjelaskan bahwa variabel independen di dalam penelitian ini dapat menjelaskan variasi variabel dependen sebesar 86,32 %. Nilai F-statistik sebesar 50.46 menunjukkan bahwa variabel independen dalam jangka panjang seperti ekspor dan impor dapat mempengaruhi PDB Indonesia.</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"C:/Users/Xvby/Documents/UAS METEDOLOGI PENELITIAN"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'DATA UAS METODOLOGI PENELITIAN.xlsx'</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(y<span class="sc">~</span>x<span class="sc">+</span>s, <span class="at">data=</span>dat)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x + s, data = dat)

Residuals:
       Min         1Q     Median         3Q        Max 
-1.375e+11 -8.624e+10 -2.904e+10  7.169e+10  2.836e+11 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)
(Intercept) -1.080e+11  9.633e+10  -1.121    0.279
x            2.551e+00  2.025e+00   1.260    0.226
s            2.507e+00  2.063e+00   1.215    0.242

Residual standard error: 1.239e+11 on 16 degrees of freedom
Multiple R-squared:  0.8632,    Adjusted R-squared:  0.8461 
F-statistic: 50.46 on 2 and 16 DF,  p-value: 1.229e-07</code></pre>
</div>
</div>
<p>Dapat dilihat dari tabel di atas bahwa, setiap kenaikan nilai ekspor (X) dengan diasumsikan nilainya 1, maka dapat meningkatkan PDB sebesar 2.551 dengan S yang sama,dan nilai impor berpengaruh positif juga pada PDB Indonesia, jika diasumsikan nilai impor (S) 1 maka PDB akan ada peningkatan 2.507.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Dalam rangka mencapai pertumbuhan ekonomi yang berkelanjutan, penting untuk memahami dampak aktivitas ekspor dan impor terhadap Produk Domestik Bruto (PDB) suatu negara. Penelitian ini fokus pada Indonesia dalam periode 2004-2022, mencakup peristiwa penting seperti krisis keuangan global 2008 dan pandemi COVID-19 2020. Diharapkan, analisis mendalam ini dapat memberikan wawasan kepada masyarakat luas untuk mengoptimalkan manfaat perdagangan internasional demi pertumbuhan ekonomi yang berkelanjutan di Indonesia.</p>
<p>Di satu sisi, peningkatan ekspor berkontribusi positif terhadap PDB. Namun, penting untuk menyadari bahwa impor juga memiliki dampak positif. Impor dapat berperan dalam merangsang pasar lokal dengan memperoleh teknologi dan pengetahuan baru dari negara lain. Meskipun demikian, perlu diingat bahwa impor dapat memberikan dampak negatif jika tidak diatur dengan kebijakan yang ketat dan sesuai. Ketidak tersediaan pengawasan yang baik terhadap kegiatan impor dapat berpotensi merugikan pasar lokal dan PDB Indonesia. Oleh karena itu, perlunya kebijakan impor yang bijaksana dan terukur menjadi esensial untuk menjaga keseimbangan dan keberlanjutan ekonomi nasional.</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Hodijah, S., &amp; Angelina, G. P. (2021). ANALISIS PENGARUH EKSPOR DAN IMPOR TERHADAP PERTUMBUHAN EKONOMI DI INDONESIA. Jurnal Online Universitas Jambi, 10, 1–10. https://online-journal.unja.ac.id</p>
<p>Puspandari, T., Priyatno, S. H., Novialum, A., &amp; Herwanti, L. (2022). Pengaruh Ekspor dan Impor terhadap Pertumbuhan Ekonomi di Indonesia. Jurnak Ilmiah Ilmu Pendidikan, 5, 1–4. https://jiip.stkipyapisdompu.ac.id</p>
<p>Multivariat &amp; Dummy regression. Retrieved January 6, 2024, from https://www.krisna.or.id/metopel/meeting3/index.html#/bandingkan-2-model</p>
<p>Nainggolan, H. F. F. F. (2023). Pengaruh Ekspor Impor Terhadap PDRB Provinsi Jawa Timur 2008-2021 [Politeknik APP Jakarta]. https://hizkiafree.github.io/</p>
<p>The World Bank. (n.d.). Retrieved January 7, 2024, from https://data.worldbank.org/indicator/NY.GDP.MKTP.CD?locations=ID</p>
<p>The World Bank. (n.d.). Retrieved January 7, 2024, from https://data.worldbank.org/indicator/NE.EXP.GNFS.CD?locations=ID</p>
<p>The World Bank. (n.d.). Retrieved January 7 2024, from https://data.worldbank.org/indicator/NE.IMP.GNFS.CD?locations=ID</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>